name: Publish to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: zettelkasten
      - name: Checkout org-roam-ui
        uses: actions/checkout@v4
        with:
          repository: ikoamu/org-roam-ui
          ref: feature/add-export-functionality
          path: ui
      - name: Copy graphdata
        run: cp -r zettelkasten/graphdata.json ui/graphdata.json

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Dependencies
        working-directory: ./ui
        run: yarn

      - name: Build stantalone
        working-directory: ./ui/standalone
        run: ./build-standalone-server.sh ../../zettelkasten

      - name: add nojekyll
        working-directory: ./ui
        run: touch ./standalone/out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: "./ui/standalone/out"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
