name: Publish to Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: yarn
      - name: Clone org-roam-ui
        run: git clone https://github.com/ikoamu/org-roam-ui.git \
          && cd org-roam-ui \
          && cp ../graphdata.json ./graphdata.json \

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build
      - name: Export
        run: yarn export
      - name: add nojekyll
        run: touch out/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
