name: Publish to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: ikoamu/org-roam-ui-hosting@main
      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     path: zettelkasten
      # - name: Checkout org-roam-ui
      #   uses: actions/checkout@v4
      #   with:
      #     repository: ikoamu/org-roam-ui
      #     ref: feature/add-export-functionality
      #     path: ui

      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "20.x"

      # - name: Setup Graphdata Generator
      #   working-directory: ./zettelkasten
      #   run: npm install

      # - name: Generate Graphdata
      #   working-directory: ./zettelkasten
      #   run: npm run generate

      # - name: Print Graphdata
      #   working-directory: ./zettelkasten
      #   run: cat ./graphdata.json

      # - name: Generate Notes
      #   working-directory: ./zettelkasten
      #   run: ./generateNotes.sh

      # - name: Print Notes
      #   working-directory: ./zettelkasten
      #   run: ls -l ./notes

      # - name: Install org-roam-ui Dependencies
      #   working-directory: ./ui
      #   run: yarn

      # - name: Build stantalone
      #   working-directory: ./ui/standalone
      #   run: ./build-standalone-server.sh ../../zettelkasten

      # - name: Add nojekyll
      #   working-directory: ./ui
      #   run: touch ./standalone/out/.nojekyll

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v2
      #   with:
      #     # Upload entire repository
      #     path: "./ui/standalone/out"

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v2
