name: Publish to Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone org-roam-ui
        run: git clone https://github.com/ikoamu/org-roam-ui.git \
          && cp ./graphdata.json ../graphdata.json \

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: yarn
          cache-dependency-path: "./org-roam-ui/package.json"
      - name: Install Dependencies
        working-directory: ./org-roam-ui
        run: yarn
      - name: Build
        working-directory: ./org-roam-ui
        run: yarn build
      - name: Export
        working-directory: ./org-roam-ui
        run: yarn export
      - name: add nojekyll
        working-directory: ./org-roam-ui
        run: touch out/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./org-roam-ui/out
