name: Publish to Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: zettelkasten
      - name: Checkout org-roam-ui
        uses: actions/checkout@v3
        with:
          repository: ikoamu/org-roam-ui
          path: ui
      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "16.x"
      - name: Test1
        run: ls -la \
          && ls -la zettelkasten \
          && ls -la ui
      - name: Copy graphdata
        run: cp -r zettelkasten/graphdata.json ui/public/graphdata.json
      - name: Test2
        run: ls -la \
          && ls -la zettelkasten \
          && ls -la ui
      # - name: Install Dependencies
      #   working-directory: ./org-roam-ui
      #   run: yarn
      # - name: Build
      #   working-directory: ./org-roam-ui
      #   run: yarn build
      # - name: Export
      #   working-directory: ./org-roam-ui
      #   run: yarn export
      # - name: add nojekyll
      #   working-directory: ./org-roam-ui
      #   run: touch out/.nojekyll
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./org-roam-ui/out
